version: '3'
services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www/html/
    links:
      - php-fpm
      - db
    networks:
      - app-network

  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./project:/var/www/html/
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - 9000:9000
    networks:
      - app-network

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge